### ISSUE TITLE
When SCAYT's enabled, opening the image dialog by doubleclick opens a dialog without the URL set

### ISSUE THREAD

**Issue by Reinmar** [WebSpellChecker/ckeditor-plugin-scayt#101]
1. Open http://cdn.ckeditor.com/4.5.0/standard-all/samples/old/replacebyclass.html
2. Enable SCAYT.
3. Doubleclick the image.

A dialog without URL is opened, because selection is lost. Works fine when SCAYT is disabled.

Reproduced on Chrome and Firefox from 4.4.0 (since the SCAYT engine update IIRC).

**Comment by WebSpellChecker** [comment]
The issue has been already reported.  https://github.com/WebSpellChecker/ckeditor-plugin-scayt/issues/98
