### ISSUE TITLE
DOM Exception 22 on iPad private browsing

### ISSUE THREAD

**Issue by scofalik** [WebSpellChecker/ckeditor-plugin-scayt#103]
When SCAYT is enabled in private browsing on iPad, it throws an error:
`QuotaExceededError: Dom exception 22: An attempt was made to add something to storage that exceeded the quota`.

The error is caused by the fact that localStorage is disabled while private browsing on iPad. This happens on iOS 8.3, Mobile Safari 8.

**Comment by WebSpellChecker** [comment]
We will look for the fix during next development sprint that is started on Monday (August 17).

**Comment by WebSpellChecker** [comment]
Closed because of duplicate.
