### ISSUE TITLE
SCAYT should not check non-editable parts of content

### ISSUE THREAD

**Issue by Reinmar** [WebSpellChecker/ckeditor-plugin-scayt#107]
1. Open http://sdk.ckeditor.com/samples/mediaembed.html
2. Enable SCAYT.
3. Paste "https://twitter.com/Philae2014/status/610047412036595712" into the editor and wait until it's auto embedded.

Actual: The "Philae" word is underlined.

Expected: It should not be as it is not an editable part.

**Comment by WebSpellChecker** [comment]
We confirm the issue. It has been reported into our internal bug tracking system. Our Web Team currently is working on the solution. The fix will be implemented in the upcoming 4.8.2 version. The WebSpellChecker.net application 4.8.2 release is scheduled for the middle of October 2015.

**Comment by Tade0** [comment]
This issue is still reproducible in 54fcc98c5d12d654c378d884d3299a5d3422cc9e.

**Comment by WebSpellChecker** [comment]
Fixed in SCAYT Core. Will be available in upcoming 4.8.2 release. Rescheduled for the middle of December 2015.

**Comment by WebSpellChecker** [comment]
The fix has been released.
