### ISSUE TITLE
Latest SCAYT copies id of editor element to the iframe

### ISSUE THREAD

**Issue by Reinmar** [WebSpellChecker/ckeditor-plugin-scayt#108]
1. Open CKEditor official sample (the one shipped in a package).
2. Enable SCAYT.
3. Weird dashed border appears around the content.

Tuns out this is caused by SCAYT adding id `editor` to the iframe element used by the editor. This is incorrect because this id is already used by element from which the editor was created. Duplicating id may lead to unpredictable issues in integrations.

**Comment by Reinmar** [comment]
This issue was reproduced with 62461da8a. Everything works fine in 6b3f5a88 which is used by CKE 4.5.3.

**Comment by WebSpellChecker** [comment]
It is known behaviour. Thank you for reporting it. We're in progress to resolve this problem. We'll let you know the status of the issue on next Monday (19th of October, 2015)

**Comment by mlewand** [comment]
Any ideas on when we can expect it to be fixed?

**Comment by WebSpellChecker** [comment]
We plan to update SCAYT plugin by the end of this week.

**Comment by WebSpellChecker** [comment]
Fixed with ac633a10074b581cec947b3cedfc270287c32efc. This is not a final commit we plan to publish for CKEditor 4.5.5. Will keep you updated.

**Comment by Tade0** [comment]
This error does occur anymore. Tested in 54fcc98c5d12d654c378d884d3299a5d3422cc9e.

**Comment by WebSpellChecker** [comment]
Fixed with ac633a1. Closed.

**Comment by WebSpellChecker** [comment]
The fix has been released.
