### ISSUE TITLE
scayt_elementsToIgnore not applying to custom elements

### ISSUE THREAD

**Issue by jaydavid** [WebSpellChecker/ckeditor-plugin-scayt#109]
Setting the scayt_elementsToIgnore setting in configuration seems to work for some elements but not others.

1. Download ckeditor standard package
2. In the sample index.html file add to the contents of the editor: &lt;placeholder&gt;asdf&lt;/placeholder&gt;
3. In the config.js add config.scayt_elementsToIgnore = 'placeholder'
4. View the sample page and enable spellcheck as you type

The editor will mark the "asdf" within its content as misspelled even though it is in a "placeholder" element which is meant to be ignored.

If you repeat the steps above with a "del" element instead of some custom one then things work as expected.

**Comment by WebSpellChecker** [comment]
Hello, jaydavid

'elementsToIgnore' specifies the names of tags that will be skipped while spell checking. 

What you mean under <placeholder>asdf</placeholder>? 

This is not valid HTML tag and it can be removed from editor document with  [ACF](http://docs.ckeditor.com/#!/guide/dev_advanced_content_filter)

Try next:
config.allowedContent = 'placeholder';
config.scayt_elementsToIgnore = 'placeholder';

**Comment by jaydavid** [comment]
Sorry, when I first authored the issue I messed up the markdown.  The misspelled text (asdf in this case) is surrounded by an html tag specified in the scayt_elementsToIgnore called "placeholder" 

&lt;placeholder&gt;asdf&lt;/placeholder&gt;

You are correct though, it is not a valid HTML tag it is a custom one.

When I combine the two settings you suggest, I am still seeing text within a "placeholder" element being checked.

**Comment by jaydavid** [comment]
Perhaps I'm misinterpreting the documentation.  Just for some added clarity, here is a sample html file in which I'm seeing the issue.  Please let me know if I'm just mistaken about how this functionality is supposed to function.

When the page is loaded, turn on spell check as you type and the "asdf" within the editor will be flagged as misspelled.

[index.txt](https://github.com/WebSpellChecker/ckeditor-plugin-scayt/files/36789/index.txt)

**Comment by WebSpellChecker** [comment]
jaydavid,

If you want to work with customConfig config inline You need to move your code to custom config file
(read more - http://docs.ckeditor.com/#!/guide/dev_configuration#)

We only can suggest You next workaround:

	<script>      
		    		
			CKEDITOR.replace( 'editor' , {
				scayt_autoStartup: true,
				allowedContent: 'placeholder',
				scayt_elementsToIgnore: 'placeholder'
			});	
			
		</script>

**Comment by jaydavid** [comment]
That seems to work - thank you!  I will apply this workaround.
