### ISSUE TITLE
Warning thrown while enabling SCAYT

### ISSUE THREAD

**Issue by Comandeer** [WebSpellChecker/ckeditor-plugin-scayt#110]
Bug in CKEditor: http://dev.ckeditor.com/ticket/13948

## Steps to reproduce 

1. Open CKEditor (hash: b34ea4de6106ce5513da723ba42c3ba52da7424a) with SCAYT plugin (hash: 54fcc98c5d12d654c378d884d3299a5d3422cc9e).
2. Open console.
3. Click "Check Speller" button and choose "Enable SCAYT".

## Expected result
SCAYT is enabled without any warnings or errors.

## Actual result
Warning `'Range.detach' is now a no-op, as per DOM (http://dom.spec.whatwg.org/#dom-range-detach).` on line 33 of http://svc.webspellchecker.net/spellcheck31/lf/scayt3/ckscayt/ckscayt.js?1447928201435 is logged into console.

## Other details (browser, OS, CKEditor version, installed plugins) 
Chrome 46/Opera 33 on Ubuntu 15.10

**Comment by jswiderski** [comment]
You can also use this pre-set https://github.com/ckeditor/ckeditor-presets/tree/wsc-test-env-4.5.5

**Comment by WebSpellChecker** [comment]
Fixed in SCAYT CORE. Will be released in v 4.9 that is scheduled for February, 2016.

**Comment by WebSpellChecker** [comment]
The fix has been released.
