### ISSUE TITLE
DOM Exception 22: Quota exeeded error

### ISSUE THREAD

**Issue by Tade0** [WebSpellChecker/ckeditor-plugin-scayt#112]
### Steps to reproduce

Open CKEditor (hash: b34ea4de6106ce5513da723ba42c3ba52da7424a) with SCAYT plugin (hash: 54fcc98).

1. Open console.
1. Click "Spell Checker" button and choose "Enable SCAYT".

### Expected result

SCAYT is enabled without any warnings or errors.

### Actual result

Error: `QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.` in http://svc.webspellchecker.net/spellcheck31/lf/scayt3/ckscayt/ckscayt.js:32

### Other details (browser, OS, CKEditor version, installed plugins)

Safari, iOS 9.

**Comment by WebSpellChecker** [comment]
This is not SCAYT's issue. This is usual behavior of applications that are used localStorage and opened in Private mode of Safari. Please be sure that the Private mode is off and try to reproduce again. SCAYT works in Safari (iOS 9) with disabled Priave mode.

Tested on Safari, iOS 9.
