### ISSUE TITLE
scayt plugin only check word length greater then 3 alphabets and in apostrophy scayt didnt work

### ISSUE THREAD

**Issue by Zohaib-Raza** [WebSpellChecker/ckeditor-plugin-scayt#113]
example , he , him , does'nt

**Comment by KremYura** [comment]
By default, SCAYT collects words with length >=4 characters. You can change behaviour by using 
`CKEDITOR.config.scayt_minWordLength` parameter.
The parameter defines minimum length of the words that will be collected from editor's text for spell checking.

Usage:
```js
// global
CKEDITOR.config.scayt_minWordLength = 3;
```
```js
// local
CKEDITOR.replace( 'container', {
    scayt_minWordLength: 3
});
```
