### ISSUE TITLE
Wrong selection after a fix and undo in nested editable

### ISSUE THREAD

**Issue by oleq** [WebSpellChecker/ckeditor-plugin-scayt#117]
1. Open `samples/old/image2/image2.html` sample.
2. Set the following HTML: 
```
<p>content</p>
<figure class="image" style="float:right"><img alt="Saturn V" src="assets/image1.jpg" width="200" />
<figcaption>a misspeled caption</figcaption>
</figure>
```
----
Then:
1. Enable SCAYT.
2. Using the context menu, fix a misspelled word in the caption.
3. Move the caret out of the widget, to `<p>cont^ent</p> ...`.
4. Undo (CTRL+Z).

## Expected:

The spell fix is undone. The selection is `...<figcaption>a [misspeled] caption</figcaption>...`.

## Actual:

The spell fix is undone. The selection is `...<figcaption>[a misspel]ed caption</figcaption>...`.

----

Tested in Safari 9.x.

**Comment by WebSpellChecker** [comment]
By default the WebSpellChecker.net products support only Internet Explorer 8+, Firefox latest, Google Chrome latest. 
Here is a link for reference: http://wiki.webspellchecker.net/doku.php?id=environments:browsers
The issue is not reproduced in the supported browsers.
