### ISSUE TITLE
GRAYT "The same word appears twice in a row" breaks formatting.

### ISSUE THREAD

**Issue by f1ames** [WebSpellChecker/ckeditor-plugin-scayt#118]
1. Turn on grayt in `/samples/js/sample.js` (`grayt_autoStartup: true`)
2. Open samples/index.html
3. Enable SCAYT.
4. Set the following HTML (in source mode):

```
<h1>Space</h1>
<p>Space is a robotic space probe built and launched by...</p>
```

Then switch back to normal mode.
## Actual:

Result HTML after GRAYT processing content looks like this: 

```
<h1>Space</h1>

<p>Space</p>

<p>is a robotic space probe built and launched by...</p>
```

So visually `<h1>Space</h1>` and `<p>Space</p>` are glued together in first line.
## Expected:

Both words (`SpaceSpace`) are underlined without any visible changes in text formatting.

---

Tested in Opera 34.0

**Comment by WebSpellChecker** [comment]
It is known issue. I've update you with the status when we begin working on the fix.

**Comment by wsc-bug-hunter** [comment]
The fix for issue has been released. Check it out in 4.9.0

**Comment by f1ames** [comment]
I am unable to reproduce the issue anymore. Thanks!
