### ISSUE TITLE
"Ignore" ignores also newly added words

### ISSUE THREAD

**Issue by Comandeer** [WebSpellChecker/ckeditor-plugin-scayt#119]
1. Open CKEditor's demo (might be http://ckeditor.com/demo)
2. Enable SCAYT.
3. Type: `asdf whatever`
4. Right click on `asdf` and choose "Ignore".
5. Place cursor at the end of text and type: `asdf more`.

**Expected:**
The second `asdf` is underlined.

**Actual:**
The second `asdf` is not underlined.

**Comment by KremYura** [comment]
Newly typed word after "Ignore" not underlined. Could you please recheck the issue? Also, to ignore all words in documents use "Ignore All" feature.

**Comment by Comandeer** [comment]
Actually it's the problem: they are **not** underlined.

I assume that "Ignore" option should just ignore the specified occurence of given word, not that occurence and all occurences that will appear in the future.

**Comment by Comandeer** [comment]
The issue is still present in the new version of SCAYT (4.8.5.0).

**Case 1:**

1. Type into editor `asdf rtyui asdf`.
2. Enable SCAYT.
3. Right click on the first `asdf` and choose "Ignore".
4. Place the cursor at the end of text and type ` asdf rtyui asdf`.

**Expected:**

The second and third `asdf` are underlined (as we chose only to ignore first).

**Actual:**

All `asdf`s are now ignored.

**Case 2:**

1. Type into editor: `asdf asdf rtyui`.
2. Enable SCAYT.
3. Right click on the first `asdf` and choose "Ignore".
4. Place the cursor at the end of text and type ` asdf rtyui asdf`.

**Expected:**

The newly typed `asdf` are underlined.

**Actual:**

They are ignored.

**Comment by wsc-julia-shaptala** [comment]
In release 4.9.1 (June 29, 2017) **Ignore** option was removed from the SCAYT default functionality. It's still available as it is for our old customers.

Going further we will keep and support only **Ignore all**.  **Ignore all** command ignores all the same words and doesn’t consider them as misspelled within the text until the page reloads.
