### ISSUE TITLE
Can't use Bold/Italic/Strike buttons with SCAYT turned on

### ISSUE THREAD

**Issue by gscarpino** [WebSpellChecker/ckeditor-plugin-scayt#121]
"WebSpellChecker commented on Oct 2, 2014
The fix has been released in version 4.6. Please find license and hosted change logs:

http://wiki.webspellchecker.net/doku.php?id=changelogs:licensed
http://wiki.webspellchecker.net/doku.php?id=changelogs:hosted

The fix is in SCAYT CORE. If you use hosted version, you already have it. If Licensed, the upgrade is needed."

Ref: https://github.com/WebSpellChecker/ckeditor-plugin-scayt/issues/79

**Comment by WebSpellChecker** [comment]
What version of CKEditor do you use?

**Comment by WebSpellChecker** [comment]
We're planning to start the investigation and fixing next development sprint that is started on Monday (January 4, 2016). It should be released in the WebSpellChecker.net v 4.9 (February, 2016)

**Comment by WebSpellChecker** [comment]
The fix has been released.
