### ISSUE TITLE
Uncaught TypeError: Cannot read property 'initialized' of undefined in ckscayt.js

### ISSUE THREAD

**Issue by pzelnip** [WebSpellChecker/ckeditor-plugin-scayt#127]
Enabling SCAYT in Ckeditor, I now get the mentioned error upon clicking into the CKeditor DIV.  CKeditor version 4.5.7.

![screen shot 2016-04-05 at 9 06 03 am](https://cloud.githubusercontent.com/assets/414933/14288966/b1855ef2-fb0d-11e5-97f6-5e599946936d.png)

**Comment by WebSpellChecker** [comment]
Thank you for provided information. We did manage to reproduce the issue. We're going to include the fix for this issue into upcoming release. We plan to release the WebSpellChecker.net application version 4.8.3.1 by the end of the next week.

**Comment by pzelnip** [comment]
Awesome thanks for the update.

**Comment by wsc-artem-abakumov** [comment]
@pzelnip The fix has been released.
