### ISSUE TITLE
Mismatched anonymous define() module

### ISSUE THREAD

**Issue by dragoscd** [WebSpellChecker/ckeditor-plugin-scayt#128]
I saw that few weeks ago, AMD support has been added to the file from https://svc.webspellchecker.net/spellcheck31/lf/scayt3/ckscayt/ckscayt.js  and that cause some conflicts now with RequireJS that we use in the application. 
The error appears when I'm leaving the view that contains CKEditor.

`require.min.js:3 Uncaught Error: Mismatched anonymous define() module: function(a) {
    return a.createModule("SaveRestore", ["WrappedSelection"], function(a, b) {
        function c(a, b) {
            return (b || document).getElementById(a)
        } 
...
`
A similar issue has been filed also here: http://dev.ckeditor.com/ticket/14597

http://requirejs.org/docs/errors.html#mismatch

This may be the cause:

`function(a, b) {
"function" == typeof define && define.amd ? define(rangy-core?, a) : "undefined" != typeof module && "object" == typeof exports ? module.exports = a(require("rangy")) : a(b.rangy)
}`

**Comment by Artyom-Abakumov** [comment]
Thank you for provided information. We did manage to reproduce the issue. We're going to include the fix for this issue into upcoming release. We plan to release the WebSpellChecker.net application version 4.8.3.2 by the end of the next week.

**Comment by artiq5** [comment]
@dragoscd The fix has been released.

**Comment by dragoscd** [comment]
Awesome, seems to be working now, thanks!!
