### ISSUE TITLE
does a config option exist to keep scayt highlights when CKE goes out of focus?

### ISSUE THREAD

**Issue by steveinatorx** [WebSpellChecker/ckeditor-plugin-scayt#129]
Using latest CKE and scayt plugin. Whenever CKE loses focus and the re-focus scayt loses its context and re-runs. Is there a way to keep the existing context and underlining via a config option?

**Comment by jalners** [comment]
Here you can find all necessary information about SCAYT parameters for CKEditor 4: [The SCAYT parameters for CKEditor 4](http://wiki.webspellchecker.net/doku.php?id=scayt_parameters_ckeditor4).

In your case you need to add "config.scayt_inlineModeImmediateMarkup = true;" to config.
