### ISSUE TITLE
New CKEditor skin adjustments.

### ISSUE THREAD

**Issue by f1ames** [WebSpellChecker/ckeditor-plugin-scayt#130]
Hello WSC team,
we are working on the new skin for CKEditor 4, which will become the default skin starting from CKEditor 4.6.0. While it only changes the look, there were a few small things to polish to make scayt plugin look good with this skin. I made some changes so everything looks smooth. Those changes concern only a new skin so the plugin will still look the same with the previous moono and other skins (in other words the plugin is visually backward compatible - if you can call it that way). The changes I introduced adds an external stylesheet to make it more flexible and to not mess the code (because in fact, these are visual changes only so should be separated anyway). I will create a PR soon, so you can review these changes.

The connected task in our bug tracker is [#14790](http://dev.ckeditor.com/ticket/14790).

**Comment by f1ames** [comment]
Created PR #131. If you need more information to proceed with this, do not hesitate to ask.

**Comment by artiq5** [comment]
@f1ames Thank you for taking the time to create pull request for our plugin. We'll review your changes and notify you about results by the end of this week.

**Comment by f1ames** [comment]
@artiq5 Thank you for the information and for taking care of the PR.

**Comment by wsc-julia-shaptala** [comment]
We have accepted your PR and we're going to include these changes to our upcoming release (4.8.5). Preliminary ETA for Release is end of August or the first week of September.

**Comment by f1ames** [comment]
That's great news, thank you.
