### ISSUE TITLE
Lost focus in ckeditor, On Click of Bold,Italic, Underline in toolbar(Scayt enabled)

### ISSUE THREAD

**Issue by murugansm** [WebSpellChecker/ckeditor-plugin-scayt#132]
1. By default we have enabled scayt in my ckeditor version (4.5.10).
2. On cmd+B, typed text should be highlighted with <strong> tag. Which it does not do as of now.
We could able to see the above use case in http://ckeditor.com/demo.
When we enable scayt and try to use **B| I | U** button we do not get the required behaviour.

**Comment by artiq5** [comment]
@murugansm issue fixed since v4.8.3
Please re-build your CKEditor with latest scayt-plugin
