### ISSUE TITLE
attributes for generated tag

### ISSUE THREAD

**Issue by chambersDon** [WebSpellChecker/ckeditor-plugin-scayt#133]
I am on a existing project that uses scayt.  We are getting 508 errors with two pieces of generated code.

This tag is generated:
```
<a title="Help" target="_blank" href="http://www.webspellchecker.net/support/scayt_user_manual.html"><img src="http://spellcheck.staffingtest.opm.gov/spellcheck/lf/scayt/i/help.png">
</a>
```

The a tag is generated multiple times and needs a different value for title.  The img tag needs an alt attribute.  I don't want to edit the source code and get out of sync.

Is there a way to configure this?  Or is there a way to suppress these tags?

I am using  version 4.4.3 of ckeditor.  I am not sure how to tell the version of scayt.  I think we paid for ckeditor but I'm not sure about scayt.

**Comment by artiq5** [comment]
Fix for this issue was released in v4.8.5
