### ISSUE TITLE
GRAYT breaks table cells

### ISSUE THREAD

**Issue by wwalc** [WebSpellChecker/ckeditor-plugin-scayt#135]
Found on StackOverflow, did not check if valid:

http://stackoverflow.com/questions/39988352/grayt-plugin-is-breaking-html-in-editor

**Comment by artiq5** [comment]
@wwalc Hello Wiktor. It is known issue in GRAYT, we have shedule bug fixing for it to the next sprint. Many thanks for take care of it!

**Comment by artiq5** [comment]
Fix for issues has been released. GRAYT not grammar check in tables anymore.
