### ISSUE TITLE
SCAYT broken in built version

### ISSUE THREAD

**Issue by Comandeer** [WebSpellChecker/ckeditor-plugin-scayt#136]
https://github.com/WebSpellChecker/ckeditor-plugin-scayt/blob/8ff8557dece993ff6f09a9785d8da65f5d8f2151/plugin.js#L288 – this line seems to cause our tests to break in built version of CKEditor:

> TypeError: Cannot read property 'editable' of undefined

It's probably caused by the fact that whole code is loaded synchronically, at once. Therefore some code could execute before real editor is correctly instantiated.

**Comment by artiq5** [comment]
Fixed here: https://github.com/WebSpellChecker/ckeditor-plugin-scayt 

Closed.
