### ISSUE TITLE
scayt autoStartup true

### ISSUE THREAD

**Issue by bertin1990** [WebSpellChecker/ckeditor-plugin-scayt#138]
When in ckeditor (4.5.3) config.js change to startup from scayt to

`config.scayt_autoStartup = true;`

The names in the scayt dialogs shows only the labels.
![bug dialog scayt](https://cloud.githubusercontent.com/assets/7288381/21225150/dcd60b58-c2cf-11e6-8e5f-9a71c86d1311.PNG)

Is this a bug?

**Comment by artiq5** [comment]
@bertin1990 Please provide us clear steps to reproduce for mentioned behavior

**Comment by wsc-bug-hunter** [comment]
@bertin1990 Hello, do you have any updates on it?

**Comment by wsc-julia-shaptala** [comment]
No clear steps to reproduce the issue. We close this issue.
