### ISSUE TITLE
Aside tag gets duplicated when ENTER_BR and SCAYT is used.

### ISSUE THREAD

**Issue by jswiderski** [WebSpellChecker/ckeditor-plugin-scayt#140]
1. Use the following configuration for the editor:
```
CKEDITOR.replace( 'Editor1', {
		enterMode : CKEDITOR.ENTER_BR,
		scayt_autoStartup : true,
		extraAllowedContent : 'aside'
});
```
2. Run the page with editor
3. Paste the following HTML in source mode and switch to WYSIWYG. 
```
This is a brief test, which I will delete shortly. This is a brief test, which I will delete shortly. This is a brief test, which I will delete shortly. This is a brief test, which I will delete shortly. This is a brief test, which I will delete shortly. This is

<aside>The quick brown fox jumped over the four score and seven years ago our fathers brought forth upon this continent half a league half a league half a league onward</aside>

a brief test, which I will delete shortly. This is a brief test, which I will delete shortly. This is a brief test, which I will delete shortly. This is a brief test, which
```
**RESULT:**
The word will be put into separate aside tag.

Please refer to https://dev.ckeditor.com/ticket/14879 and Nowy.html sample attached there.
All you need to do is put this file into `ckeditor/samples` folder, run it and paste the above HTML.

It is possible that this issue no longer occurs in latest SCAYT which CKEditor doesn't use yet. Could you guys confirm that this problem is/isn't reproducible in latest SCAYT?

**Comment by wsc-bug-hunter** [comment]
Hello @jswiderski Mentioned issue already fixed and will be released in upcoming release v.4.8.7

**Comment by wsc-bug-hunter** [comment]
This Monday (Feb 27, 2017) we released a new version of WebSpellChecker application (4.8.7)

Fix for the reported issue is available in master branch or using v.4.8.7 tag:

https://github.com/WebSpellChecker/ckeditor-plugin-scayt/tree/release.4.8.7.0
