### ISSUE TITLE
SCAYT couldn't be activated when in a frame

### ISSUE THREAD

**Issue by ppermezel-solucom** [WebSpellChecker/ckeditor-plugin-scayt#142]
I've discovered that SCAYT cannot be activated when the HTML document that contains the CK editor instance is itself in a legacy frameset. However it works in a iframe.
Does anyone knows how to correct this bug?

- Inside a frame (KO): http://jsbin.com/civihu/5/edit?html,output
- Inside an iframe (OK) : http://jsbin.com/kuzufos/edit?html,output
- Without frame (OK): http://nightly.ckeditor.com/17-03-22-07-08/standard/samples/

**Comment by ppermezel-solucom** [comment]
Sorry now that I check again it seems to works... :-/ I close this issue.

**Comment by wsc-bug-hunter** [comment]
@ppermezel-solucom 
We are glad to hear that the SCAYT works for you well.
Please let us know if you have any questions or comments.

Best Wishes,
