### ISSUE TITLE
various CKEditor versions, issue is when reloading text into div, spell check stops working.

### ISSUE THREAD

**Issue by dcparham** [WebSpellChecker/ckeditor-plugin-scayt#144]
Hello, i am using CKEditor 4.5.11 Standard this time, but this issue occurs when using Nightly build, and Full version 4.6.2: i populate a div with text and the toolbar loads. Spell Check works first time; but if i spell check and save to the db, when i reload the text box the Spell Check opens and shows no text. So, refresh the whole page, not just close and reopen the dialog holding the text box; but refresh the whole site - and populate div with db info, spell check works. config.js, and ckeditor.js are unchanged, everything is out of the box. Can you help?

**Comment by wsc-bug-hunter** [comment]
David, as we mentioned it email to you  for further investigation, our team would need to have at least a demo page or test account in your system so we can try to reproduce the problem from our side.

**Comment by wsc-julia-shaptala** [comment]
Since there is no response since April 2017, we close this one.
