### ISSUE TITLE
ckeditor scayt throws Uncaught Error: Error in Rangy WrappedRange module: createRange(): Parameter must be a Window object or DOM node

### ISSUE THREAD

**Issue by GnanaprakashChandiran** [WebSpellChecker/ckeditor-plugin-scayt#147]
I am using scayt in the ckeditor as external plugin. I am able to add and save the new content. type some text, close ckeditor before validate that text. Please help me if anyone know solution?

**Comment by GnanaprakashChandiran** [comment]
![image](https://cloud.githubusercontent.com/assets/14121961/26629864/e07c9f9e-4621-11e7-81d2-5dd2fe576a58.png)

**Comment by wsc-julia-shaptala** [comment]
This is a duplicated issue. The original one is #141.
