### ISSUE TITLE
SCAYT leaves underlined word after CKEditor replace dialog corrects it.

### ISSUE THREAD

**Issue by jswiderski** [WebSpellChecker/ckeditor-plugin-scayt#148]
We had this issue reported before https://dev.ckeditor.com/ticket/5700 but it seems it has come back.

To reproduce:
1. Clear editor content and stype few misspelled words.
2. Enable SCAYT
3. Open replace dialog and find/replace incorrect word with correct one.
Result: correct word stays underlined.

I have also tried firing change event in this line https://github.com/ckeditor/ckeditor-dev/blob/master/plugins/find/dialogs/find.js#L506 hoping that it will solve the problem but that didn't help. You guys most likely don't use that editor event.

If some other event, that you need, should be fired here, please let us know.

**Comment by jalners** [comment]
Let us investigate this issue as this fix was done a while ago (7 years ago). As soon as we have any results, we will provide you with ETA for the fix.

**Comment by jalners** [comment]
We added fix for this issue.
[SCAYT leaves underlined word after CKEditor replace dialog corrects it.](https://github.com/WebSpellChecker/ckeditor-plugin-scayt/commit/bf46eaa2d06fbdb69b26dab9ec0be9846541baa5)

**Comment by wsc-julia-shaptala** [comment]
Please be informed that the fix has already been included in our release 4.9.2.
