### ISSUE TITLE
Chrome. Correcting word in widget moves focus to another editable.

### ISSUE THREAD

**Issue by jswiderski** [WebSpellChecker/ckeditor-plugin-scayt#153]
1. Open https://sdk.ckeditor.com/samples/simplebox.html
2. Clean the line "Foo bar." in first simplebox widget
3. Enable Scayt
4. Type "Missspelled " (press space behind the word)
5. Click in the middle of misspelled word - "Miss^spelled "
6. Press Backspace

**Result:**  the corrected word jumps to top to another editable resulting in "Titlemissspelled ".

I was only able to reproduce this issue in Chrome and i had to follow the above steps exactly. 

Please also see the attached video: [2017-12-11_1541.zip](https://github.com/WebSpellChecker/ckeditor-plugin-scayt/files/1548133/2017-12-11_1541.zip)

**Comment by jswiderski** [comment]
Could be related to issue #152

**Comment by wsc-bug-hunter** [comment]
Hello @jswiderski 
Thank you so much for provided details. We have reproduced and created an issue on our side.
Regards,
WebSpellChecker Team

**Comment by wsc-julia-shaptala** [comment]
The issue has been fixed as a part of WSC 5.0.0.
