### ISSUE TITLE
SCAYT throw an error on IE8 and doesn't work

### ISSUE THREAD

**Issue by msamsel** [WebSpellChecker/ckeditor-plugin-scayt#155]
Hi

I checked the SCAYT under IE8 browser in CKEditor and it seems to doesn't work.
* After opening language option there is an error in console.
* Also there is no highlight of the wrong word.

Issue also appears on previous version of the plugin (I checked 4.6.0 and 4.8.0 of CKEditor release).
https://cdn.ckeditor.com/4.8.0/full-all/samples/
![screen shot 2018-02-12 at 10 30 18](https://user-images.githubusercontent.com/9017322/36090598-489c07fc-0fe1-11e8-8fec-2ba7180209e5.png)

**Comment by jacekbogdanski** [comment]
I can reproduce it on IE10. Getting error:
`SCRIPT5007: Unable to get property '$' of undefined or null reference 
options.js, line 4 character 238
`
after opening language options.

**Comment by wsc-bug-hunter** [comment]
Hello guys, 
We're planning to start the investigation and fixing stage of the issue in this development sprint that was started yesterday (Feb 13, 2017). It should be released in the WebSpellchecker Application v 5.0.0 (March, 2017)

**Comment by mlewand** [comment]
We could also reproduce it on IE10.

Any updates on that? It breaks the SCAYT for IE8-IE10 users.

**Comment by wsc-bug-hunter** [comment]
Hello @mlewand . As we mentioned before we are currently working on this issue.

**Comment by kapilgupta77** [comment]
What is the release date of 5.0.0?

**Comment by wsc-julia-shaptala** [comment]
This was fixed as a part of release WSC 5.0.0 on May 16, 2018.
