### ISSUE TITLE
When using a inline editor inside a iframe the entire page gets spellchecked

### ISSUE THREAD

**Issue by richardsandstrom** [WebSpellChecker/ckeditor-plugin-scayt#157]
I'm using the CKEditor as an inline editor but the editor is placed inside a iframe. 

This causes the entire page to be spellchecked which is not desired. This also causes severe performance issues and several gfx issues.

Looks like the issue comes from line 1258 ("var textContainer = ..."). It should be a check here if the editor is in inline mode or not.

**Comment by wsc-bug-hunter** [comment]
Hello @richardsandstrom ,

Thank you so much for your request.

We are working on your request but we need additional information from your side:

1. Could you please provide the sample_page where we can reproduce the issue?
or
2. Could you please create a sample page with https://jsfiddle.net/

We are looking forward to your reply.

Regards,
The WebSpellChecker Team

**Comment by artem-skolota** [comment]
This issue is closed due to lack of information from the user.

Regards,
WebSpellChecker Team
