### ISSUE TITLE
Some doc links contain placeholders instead of links

### ISSUE THREAD

**Issue by mlewand** [WebSpellChecker/ckeditor-plugin-scayt#158]
Version 5.x.x introduced couple of placeholders rather than real links, like this one: https://github.com/WebSpellChecker/ckeditor-plugin-scayt/blob/fff19b3c00830662e06c03517e50d110caf20e21/plugin.js#L1852

I believe it's a leftover from a build process? Most of other links are linked correctly.

**Comment by wsc-julia-shaptala** [comment]
Thank you for reporting this. We will check this issue and get back with comments.
