### ISSUE TITLE
Strange formatting issues with SCAYT

### ISSUE THREAD

**Issue by KenHaynes** [WebSpellChecker/ckeditor-plugin-scayt#162]
Yesterday morning, we started getting strange formatting errors on our website and they persist today. This includes the shrinking of tables, and red underlining under some text on some pages, including sub-headings. We disabled SCAYT and this resolved the issue. 

Interestingly, this issue not only affected our public site, it also affected clients who have our system self-host and our internal test servers.

We value to the use of SCAYT and would like to continue using it. Does anyone have any idea why this suddenly started to happen?

CKEditor 4.3.4 does not have the issue. As far as we can tell, this issue only applies to versions of CKEditor higher than 4.3.4. We have tested SCAYT with the following versions and can confirm that this issue exists for us, in all of them:

- 4.4.5
- 4.9.2
- 4.5.10
- 4.10

We have not changed our website code for over three weeks.

Many thanks.

**Comment by artem-abakumov** [comment]
@KenHaynes  Thank you for contacting us. Our technical specialist will take a look on it immediately. Could you please share us with some public page when we can replicate the issue, screenshoots and steps to reproduce it.

Kind regards,

**Comment by KenHaynes** [comment]
Thank you.

Our system does not have a public interface but we can setup an account for you to give you access, but I will need to provide these details to you privately.

**Comment by wsc-julia-shaptala** [comment]
Hi @KenHaynes,

The issue appeared after our recent release. We were able to reproduce it, and going to fix it by the beginning of the next week if the verification tests go well. We keep you posted.

Regards,

**Comment by KenHaynes** [comment]
Thanks Julia.

**Comment by artem-abakumov** [comment]
The issue has been fixed as a part of WSC Release 5.2.0.4. @KenHaynes Please re-check it on your side.
