### ISSUE TITLE
CKEDITOR spell check loading... error.Not showing suggestions

### ISSUE THREAD

**Issue by shubhanshujaiswal123** [WebSpellChecker/ckeditor-plugin-scayt#163]
If I try to see the suggestion of any word then its only giving me loading ..
can you please tell me whats the issue and how it can be fixed ?

![image](https://user-images.githubusercontent.com/16736939/51429134-95942500-1c31-11e9-8808-49d76137a015.png)
![image 1](https://user-images.githubusercontent.com/16736939/51429135-962cbb80-1c31-11e9-9438-35ea4155249a.png)

**Comment by wsc-julia-shaptala** [comment]
I'm closing this issue as this one is for another plugin, called WSC dialog for CKEditor. The duplicated issue has been already opened there.
