### ISSUE TITLE
Not working from localhost

### ISSUE THREAD

**Issue by engineering-this** [WebSpellChecker/ckeditor-plugin-scayt#164]
This is not technically an issue with SCAYT plugin itself, but with server configuration.

## Steps to reproduce.

1. Open html file with CKEditor from localhost.
2. Enable SCAYT.
3. Write something that should be marked as misspelled.

## Expected

Mistakes are highlighted.

## Unexpected

Error is logged in console, mistakes are not highlighted.
![screenshot 2019-01-22 at 12 30 01](https://user-images.githubusercontent.com/23366849/51532837-779d0f00-1e41-11e9-9a44-45b0757a95c4.png)

When opening from local IP everything works.

**Comment by wsc-julia-shaptala** [comment]
Hi @engineering-this,
Thank you for reporting the issue with the steps to reproduce. We do confirm that we had that issue. This one is already addressed and resolved. It was related to the usage limitations for the free services.
