### ISSUE TITLE
Use CKEDITOR.getUrl when referencing style sheets

### ISSUE THREAD

**Issue by glen-84** [WebSpellChecker/ckeditor-plugin-scayt#166]
`scayt.css` and `dialog.css` are referenced without using [CKEDITOR.getUrl](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html#method-getUrl).

I can send a PR, but it'll probably be a lot faster for you to just make the changes yourself (2 lines).

See also:
  * https://github.com/WebSpellChecker/ckeditor-plugin-wsc/issues/55
  * https://github.com/ckeditor/ckeditor-dev/issues/1194

**Comment by wsc-julia-shaptala** [comment]
Hi @glen-84, thank you for your suggestion. We have added this improvement to our product backlog. We will add this fix in scope of other changes that will be required for this plugin. The procedure of the plugins updates depends on CKEditor's releases as well. Even if we make the change, this change must be included by CKEditor as a part of their release. As for now we do not have ETA for the update from our side. But we will keep you posted.

**Comment by wsc-julia-shaptala** [comment]
@glen-84, we will add this small enhancement as a part of our next release 5.4.0. ETA: end of March, beginning of April 2019.

**Comment by artem-abakumov** [comment]
@glen-84 5.4.0 was released. Enhancement was included.

**Comment by artem-abakumov** [comment]
@glen-84 Please note that change will be included to the next minor CKEditor release.

But if you want it ASAP you can build CKEditor with or latest plugin using next manual:

### Checkout CKEditor 4+ from github.com
1. Create folder: ‘ckeditor’
2. Open Git Bash
3. In Git Bash: go to ‘ckeditor’ local folder: cd ../ckeditor
4. Perform for testing purpose: git clone https://github.com/ckeditor/ckeditor-dev.git
5. Perform for delivery purpose: 
git clone https://github.com/ckeditor/ckeditor-dev.git
git checkout tags/number_of_tag
6. Add SCAYT and WSC plugins
7. Go to checked out local folder: 
cd ../ckeditor/ckeditor-dev/plugins

### Clone scayt and wsc plugins
1. Clone scayt and wsc plugins
git clone https://github.com/WebSpellChecker/ckeditor-plugin-scayt.git scayt
git clone https://github.com/WebSpellChecker/ckeditor-plugin-wsc.git  wsc
(if you need clone not a master branch, you need to use next command in GitBush:
2. git clone -b another_branch https://github.com/WebSpellChecker/ckeditor-plugin-scayt.git )
3. Go to checked out local folder: cd ../ckeditor/ckeditor-dev
4. Update config.js file with: 'scayt,' + and 'wsc,' + before selectall and wysiwygarea correspondingly

### Build CKEditor 4
1. Go to builder folder: cd ../ckeditor/ckeditor-dev/dev/builder/
2. Update …/dev/builder/build-config.js file with: scayt: 1, and wsc: 1, before selectall and wysiwygarea correspondingly
3. cd ../ckeditor/ckeditor-dev/dev/builder using GitBush
4. Build CKEditor 4: sh build.sh using GitBush
5. Builded CKEditor 4 is located in ‘release’ folder

**Comment by glen-84** [comment]
Thank you! 🙂
