### ISSUE TITLE
Scayt is not working for options,language,Dictionaries,About pages are not working. OK an Cancel button are disabled 

### ISSUE THREAD

**Issue by madhurirode21** [WebSpellChecker/ckeditor-plugin-scayt#168]
I have done all setting for plugin scayt.
But still when I click on language or any other option from scayt plugin, dialog is getting opened but when I click on OK or Cancel button, nothing is happening.

Even On language dialog, its not listing languages suppoted.

![image](https://user-images.githubusercontent.com/40823392/57182121-49f04900-6eb9-11e9-93aa-895552f4aaf2.png)

Even all buttons on Dictionaries tab are not working.

![image](https://user-images.githubusercontent.com/40823392/57182127-68eedb00-6eb9-11e9-89ab-5000c1601aab.png)

var editor = CKEDITOR.replace(elemId, {
        height: '200',
        width: '650',
        resize_minHeight: 310,
        resize_minWidth: 650,
        entities_processNumerical: true,
        enterMode: 'div',
        toolbarStartupExpanded: true,
        format_tags: 'div;p;h1;h2;h3;h4;h5;h6',
        pasteFromWordRemoveFontStyles: false,
        pasteFromWordRemoveStyles: false,
        skin: 'kama',
        font_names: 'Arial;Comic Sans MS;Courier New;Tahoma;Times New Roman;Verdana',
        font_defaultLabel: 'Arial',
        fontSize_defaultLabel: '12px',
        language:locale,
	scayt_autoStartup: true,
        extraPlugins: 'scayt',
	disableNativeSpellChecker: false,
        menu_groups: 	'clipboard,form,tablecell,tablecellproperties,tablerow,tablecolumn,table,anchor,link,flash,checkbox,radio,textfield,hiddenfield,imagebutton,button,select,textarea,dialog, dialogui,floatpanel,menu,menubutton,panel',
        removePlugins: 'elementspath',
        uiColor: '#F1F1F1',
        keystrokes: [[CKEDITOR.CTRL + CKEDITOR.ALT + 13/*Enter*/, 'maximize'], [CKEDITOR.CTRL + CKEDITOR.ALT + 108/*Enter*/, 'maximize'], [CKEDITOR.CTRL + 90 /*Z*/, 'undo'], [CKEDITOR.CTRL + 89 /*Y*/, 'redo'], [CKEDITOR.CTRL + CKEDITOR.SHIFT + 90 /*Z*/, 'redo'], [CKEDITOR.CTRL + 66 /*B*/, 'bold'], [CKEDITOR.CTRL + 73 /*I*/, 'italic'], [CKEDITOR.CTRL + 76 /*L*/, 'link'], [CKEDITOR.CTRL + 85 /*U*/, 'underline']],
        toolbar: toolbarConfig || ""
    });

Please help to solve this issue.

**Comment by MBiatov** [comment]
Hi @madhurirode21 thank you for your report. Could you please tell us your version of CKEDITOR and SCAYT. Also, please provide .har file with record of your session.

**Comment by MBiatov** [comment]
Hello, @madhurirode21. We would like to check whether you still experience the issue with dialog. Do you need any additional help from our team? If the issue is still pressing for you, please provide us with the requested information.

**Comment by jshaptala** [comment]
Since there is no response more for a year, we will close this request.
