### ISSUE TITLE
Better support for multilanguage content

### ISSUE THREAD

**Issue by wwalc** [WebSpellChecker/ckeditor-plugin-scayt#17]
I initially reported it in http://dev.ckeditor.com/ticket/10888 but that's not the right issue tracker :-) so here it goes:

When I try the sample of CKEditor 4.3 Beta with the [language](http://ckeditor.com/addon/language) plugin enabled, enter there content in a different language:

    <span dir="ltr" lang="es">
    El invierno pasado estuvo tan fr&iacute;o que literalmente se form&oacute; hielo en mi barba.&nbsp;
    </span>

and then start SCAYT, it will underline the whole text, even though it has the proper Spanish dictionary included. It happens because it treats the whole content as if it was written in English.

**Comment by WebSpellChecker** [comment]
The feature has been implemented in the WebSpellChecker.net version 4.8.1. Please find the change log: http://wiki.webspellchecker.net/doku.php?id=changelogs:licensed  (Enhancement. Support of CKEditor's Language plugin)
