### ISSUE TITLE
Embedded image reload from servers on every key press and mouse clicks

### ISSUE THREAD

**Issue by erandac** [WebSpellChecker/ckeditor-plugin-scayt#170]
Embedded images continuously reloading from servers on every key press while having spell checker enabled.

You can reproduce the issue as follow.

1. Embed a image into ckeditor using built in image properties plugin
`<img src="https://dummyimage.com/600x400/b34fb3/ffae00&text=Test+CK+Editor+scayt" />
`
2. Open Google Chrome developer tools and click network tab

3. Tick "Disable Cache" to simulate images do not send cache header from the server

4. Enable Spell Checker

5. Type text into the editor

6. inspect the network calls that continuously sending to server for embed images.

Disabling Spell Checker dose not have this issue.

![image](https://user-images.githubusercontent.com/3974037/63146245-f80ea180-c017-11e9-916c-5b060f75c55a.png)

**Comment by jalners** [comment]
For some internal causes we work with `innerHTML` functionality and you can see this image reloading. You can add next code for avoid this:
```
CKEDITOR.config.scayt_handleCheckDirty = false;
CKEDITOR.config.scayt_handleUndoRedo = false;
```

**Comment by jalners** [comment]
Hi @erandac,
Have you tried suggested workaround? Did it work?

**Comment by andrewzheludkov** [comment]
> Hi @erandac, Have you tried suggested workaround? Did it work?

Have the same issue, embedded image continuously reloads from the server
Initiator https://svc.webspellchecker.net/spellcheck31/wscbundle/wscbundle.js
Every time the key is pressed image reloads and this does not help
`CKEDITOR.config.scayt_handleCheckDirty = false;
CKEDITOR.config.scayt_handleUndoRedo = false;`

**Comment by okulykova** [comment]
Hi @andrewzheludkov,

Please try using the suggested workaround above, and let us know if the issue has been resolved.

**Comment by andrewzheludkov** [comment]
CKEDITOR.config.scayt_handleCheckDirty = false;
CKEDITOR.config.scayt_handleUndoRedo = false;
no effect( 
mBs of traffic increasing.
I have a lot of small 20-50 kB pictures, like user avatars in editor text (by cke mention plugin) and they produce traffic.
Tried to add img html tag to ignore spellcheck, tried to wrap the image with <del> html tag (<del> html tag do prevent from spellcheck) but its not about spellchecking, looks like its about all html content of ckeditor

**Comment by andrewzheludkov** [comment]
> Hi @andrewzheludkov,
> 
> Please try using the suggested workaround above, and let us know if the issue has been resolved.

Якщо зручніше - можна соловїною) По вашому лого це зрозуміло)

**Comment by okulykova** [comment]
Доброго дня, @andrewzheludkov, ми з України та могли б спілкуватися солов'їною надалі. Але, GitHub - відкритий ресурс і, можливо, наша відповідь буде також корисною іншим користувачам. Тому, за правилами, ми відповідаємо тут англійською)

The SCAYT plugin for CKEditor 4 is provided as is. We don't release specific updates or features for it. Thus, we can't provide a fix for the mentioned issue.

If you are interested in spell and grammar check, you can consider our other product, [WProofreader spell and grammar check SDK](https://webspellchecker.com/). This is an alternative product for SCAYT with extra functionality and flexibility including autocomplete suggestions (aka “text prediction”), spelling autocorrect and style guide suggestions. Also, there are API options for advanced configurations. You can see how it works on our [demo page](https://demos.webspellchecker.com/wproofreader-ckeditor4.html). 

Moreover, unlike SCAYT, you can use the WProofreader component for CKEditor 4 with other text editors, HTML editable controls, and elements with a contenteditable attribute. 

WProofreader is our main product and we're constantly working on its improvements (e.g. by adding new features and updating the existing ones). It's not a free service. Here the cost depends on the number of words processed per year. If you are interested, you can get more details by [contacting us](https://webspellchecker.com/contact-us/).
