### ISSUE TITLE
Programmatically Disable 

### ISSUE THREAD

**Issue by SamKirkland** [WebSpellChecker/ckeditor-plugin-scayt#172]
In the UI we have the option to disable spell checking using "Disable SCAYT", is there a way of doing this programmatically via javascript?

I'd like for scayt_autoStartup to be enabled on startup, but another action to disable the plugin outside of the CKEditor UI.

Thanks!

**Comment by jalners** [comment]
Hi @SamKirkland,
You can use next code for enabling/disabling SCAYT: `CKEDITOR.instances.editor.execCommand('scaytToggle');` where `editor` is a reference to the CKEditor editor (you can get it from `CKEDITOR.instances`).

**Comment by SamKirkland** [comment]
That's exactly what I need. Thanks!
