### ISSUE TITLE
Disable some of the options inside the Scayt dropdown list inside CKEditor 4

### ISSUE THREAD

**Issue by jmonfu** [WebSpellChecker/ckeditor-plugin-scayt#173]
I am using the built in 'Scayt' to spell check the text inside my React application.

toolbar: [
{ name: 'editing', items: ['Find', 'Replace', '-', 'SelectAll', 'Scayt'] },

I have a question, is it possible to remove some of the options for the dropdown list it comes with?

I would like to just have Languages displayed, is that possible?

![spellcheck](https://user-images.githubusercontent.com/163650/66372736-09848200-e9a7-11e9-99b9-88fbc96a171a.png)

**Comment by wsc-julia-shaptala** [comment]
Hi @jmonfu,

You can remove only part of the items from this dropdown. And this can be done by adding the next parameters to CKEditor config.js file:
```
config.scayt_uiTabs = ‘0,1,0’; 
config.removePlugins = ‘wsc’;
```
`config.scayt_uiTabs` is responsible for displaying Options, Languages and Dictionaries. **Check Spelling** is a different plugin of WebSpellChecker for CKEditor. It provides spell checking in a separate dialog. To remove it, you need to use `config.removePlugins` as shown above.

There is no public option to remove 'Disable SCAYT' as users should have an option to turn off spelling check if needed.

You are not able to remove 'About SCAYT' in the free version of the plugins. If you are interested in having the extended functionality without banner ad and daily usage limitations, please fee free to contact us about the commercial options.

**Comment by jmonfu** [comment]
Thank you Julia, will contact you

**Comment by wsc-julia-shaptala** [comment]
Great. Here is our [contact us](https://webspellchecker.com/contact-us/) page.
