### ISSUE TITLE
Alphabetical sorting of personal dictionary

### ISSUE THREAD

**Issue by danielwirz** [WebSpellChecker/ckeditor-plugin-scayt#180]
Hello

When new words are added to a dictionary, they are appended to the existing dictionary, which results in a time-based sorting, where the newest word is at the last position in the dictionary. 

Would it be possible to sort the dictionary alphabetically?

Thanks a lot and best regards

**Comment by jshaptala** [comment]
Hi @danielwirz,

Right now, the newly added word will be placed in the last position on the list. And there is no alphabetical sorting available.

I will discuss your request with our technical team to see what we can do and when we can add such an option. But more likely, it will be added only to the WProofreader add-on for rich text editors and not to the SCAYT plugin.

I will keep you posted.

Regards,

**Comment by jshaptala** [comment]
@jshaptala we've added this task to our backlog and plan to take care of it probably at the beginning of the next year. It will be implemented on the back-end. Thus, no updates are required in the plugin. We will notify you once this improvement is available.

**Comment by danielwirz** [comment]
hi @jshaptala 

that's great, thanks a lot!

best regards & have a great day

**Comment by jshaptala** [comment]
Hi @danielwirz, 
Today we released the improvement for alphabetical sorting words in user-level dictionaries. The current algorithm is not ideal yet and we do plan to add improvements.
