### ISSUE TITLE
Soft hyphens should not be stored in user dictionary

### ISSUE THREAD

**Issue by danielwirz** [WebSpellChecker/ckeditor-plugin-scayt#181]
Hello

When a word is added to a dictionary by right-clicking > Add Word, the word is added as it is and contains all `&shy;` entities. 
The same word without `&shy;` entities is then not recognized by the spell checker, which leads to it being marked as an error. 

When adding a word in the dialog `&shy;` entities are not allowed. 
Adding this validation/filter to the right-click add function would probably solve this problem.

Thanks and best regards
daniel

**Comment by jshaptala** [comment]
@danielwirz,

Our QA team will re-check this behavior on Monday and we will get back to you with comments.

Regards,

**Comment by jshaptala** [comment]
Hi @danielwirz, today our team released the fix for proper handling soft hyphen `&shy;` when using user-level dictionaries. Please confirm if it works now.
