### ISSUE TITLE
Usefulness of some config values

### ISSUE THREAD

**Issue by duchenean** [WebSpellChecker/ckeditor-plugin-scayt#184]
Hello there (@jalners ?),

We are working to integrate some config values in our package to use the cloud or self-hosted version of webspellchecker.

Are these parameters still used ? (It looks like it's some legacy code from SCAYT 3)

`scayt_serviceProtocol`
`scayt_serviceHost`
`scayt_servicePort`
`scayt_servicePath`

https://github.com/WebSpellChecker/ckeditor-plugin-scayt/blob/0e3a94a7db581f8773266563ee6c6536cab412a9/plugin.js#L676

https://github.com/WebSpellChecker/ckeditor-plugin-scayt/blob/0e3a94a7db581f8773266563ee6c6536cab412a9/plugin.js#L680

https://github.com/WebSpellChecker/ckeditor-plugin-scayt/blob/0e3a94a7db581f8773266563ee6c6536cab412a9/plugin.js#L684

https://github.com/WebSpellChecker/ckeditor-plugin-scayt/blob/0e3a94a7db581f8773266563ee6c6536cab412a9/plugin.js#L688

FYI it's also mentioned in the docs : 
https://docs.webspellchecker.net/display/WebSpellCheckerServer55x/SCAYT+Parameters+for+CKEditor+4

Is it enough to just use the `scayt_srcUrl` for the self-hosted version ?

https://github.com/WebSpellChecker/ckeditor-plugin-scayt/blob/0e3a94a7db581f8773266563ee6c6536cab412a9/plugin.js#L704

Thank you !

**Comment by jalners** [comment]
Hi @duchenean,

- `scayt_srcUrl` value sets the URL to `SCAYT core`.
- `scayt_serviceProtocol`, `scayt_serviceHost`, `scayt_servicePort`, `scayt_servicePath` values are about `WebSpellChecker service`.
 
You can configure SCAYT plugin in different ways:
- Download `SCAYT core` from one place (for instance from your development localhost).
- Use `WebSpellChecker service` from another place (for instance from your company server).

For such variability, all these options were added.
