### ISSUE TITLE
Wsc-scsyt popup is showing 

### ISSUE THREAD

**Issue by pushpanjali-patil** [WebSpellChecker/ckeditor-plugin-scayt#187]
while right click on spell check suggestions some ad dialog wscspellchecker is showing with contextmenu

**Comment by jshaptala** [comment]
@pushpanjali-patil please provide more details about your request:

- the exact product that you use
- screenshots demonstrating the issue
- steps to reproduce the issue

Thanks,

**Comment by pushpanjali-patil** [comment]
![image](https://user-images.githubusercontent.com/56927198/225878330-6b0e8a5f-8f77-4096-a19b-f27c3c14c2f3.png)

![image](https://user-images.githubusercontent.com/56927198/225879272-f47f8804-1c92-44b9-aff8-3f40d63af2b4.png)

please see attached image for the same that extra dialog is showing while checking suggestions for correcting wrong words

**Comment by okulykova** [comment]
@pushpanjali-patil Thank you for sharing the screenshots. As we can see, you are using a free SCAYT plugin for CKEditor 4. Please note that the free version of this plugin is provided with a banner ad as well as daily usage limitations based on the amount of the processed text during the day. As soon as this limit is reached, the spell checking option is blocked until the next day.

If you want to remove the banner ad and daily usage limitations, you can consider upgrading to the full (paid) version. If you are interested, please contact our sales team https://webspellchecker.com/contact-us/. They will provide all the necessary information.

If it's not an option for you, you can remove the SCAYT plugin. To do so, please add the **removePlugins** parameter into the CKEditor config.js file as shown below.

**config.removePlugins ='scayt';**
