### ISSUE TITLE
spellchecking is not working

### ISSUE THREAD

**Issue by pushpanjali-patil** [WebSpellChecker/ckeditor-plugin-scayt#188]
spell check in built functionality is not working for chorme and edge Browers 
after using below properties:
disableNativeSpellChecker: false,  
 scayt_autoStartup: true,

**Comment by okulykova** [comment]
@pushpanjali-patil, could you please provide some additional information?

1. Please specify the CKEditor version you have. Run **CKEDITOR.version** in your browser's console.
2. Do we understand correctly that currently the native browser spell checker is not working?
3. Each of the mentioned properties is aimed at enabling a different spell checker (the native browser spell checker in the first case and the SCAYT plugin in the second one). Could you please specify what you expect to see as a result after enabling both of them?

Thank you.

**Comment by pushpanjali-patil** [comment]
we are using Ckeditor4 and package version is 2.3.0 actually native spellchecker is not working in chrome and edge browser also please find below image 
<img width="752" alt="Image20230323160638" src="https://user-images.githubusercontent.com/56927198/227177863-f450c0db-3b8c-4b3e-8377-2e2ff66c2d45.png">

so if you see in this image its showing suggestions for incorrect words but for same application on chrome browser its not showing and other users also its not showing on edge and chrome both

**Comment by okulykova** [comment]
@pushpanjali-patil, thank you for providing the details.

Please clear the browser's local storage. To do so, please run **localStorage.clear()** in the DevTools console tab.

Then try checking/proofreading the text again.

**Comment by pushpanjali-patil** [comment]
im not using scayt im using nativespellchecker so this browsers default spell checker is not working for ckeditor4

**Comment by okulykova** [comment]
@pushpanjali-patil, Please note that WebSpellChecker proofreading service is not a part of CKEditor but a standalone solution. As you are using the native browser spell checker, which is configured using CKEditor 4 options, then you should contact the CKEditor support team to get the necessary information: https://support.ckeditor.com/hc/en-us/requests/new
