### ISSUE TITLE
how can we configure code for free trial version webspellchecker 

### ISSUE THREAD

**Issue by pushpanjali-patil** [WebSpellChecker/ckeditor-plugin-scayt#189]
I have singed up WebSpellcheck for spell checker in CkEditor, i have service code and  it has 14 days trail period.
so i want to configure that code in my local code in ckeditor4 can you please share me any demo link to use that code.

**Comment by okulykova** [comment]
@pushpanjali-patil, we are glad that you decided to test the full potential of the SCAYT plugin for CKEditor 4. Please note that we provide support via email. 

Could you please submit your request using https://webspellchecker.com/contact-us/ form?

**Comment by pushpanjali-patil** [comment]
already my manager has signed up for webspellcheker and i got service code also so now i have to configure that code to use webspellchecker so i need help for that like how to configure it and use it?

**Comment by okulykova** [comment]
@pushpanjali-patil, as was mentioned previously, we provide support via email only for privacy policy reasons. 

I've already provided our response for you via email regarding the SCAYT plugin for CKEditor 4 configuration for your subscription (if you haven't received it, please check your spam folder).

**Comment by pushpanjali-patil** [comment]
hi im using SCAYT plugin trial version but still unable to see toolbar button ABC
![image](https://github.com/WebSpellChecker/ckeditor-plugin-scayt/assets/56927198/86c82617-6b50-484c-8456-0a7b6cd0fd51)

**Comment by okulykova** [comment]
@pushpanjali-patil, thank you for sending your request via email as well.  We've already provided our response. We will proceed with all our further communication there. This topic is considered to be closed.
