### ISSUE TITLE
Scayt removes styled spans when correcting misspelled words

### ISSUE THREAD

**Issue by jswiderski** [WebSpellChecker/ckeditor-plugin-scayt#20]
1. Open api.html sample in Blink, Webkit or Firefox
2. Enable SCAYT
3. Insert below text in textarea 
   &lt;span style="color:red"&gt;red&lt;/span&gt;
4. Select 'om' from "This is s[om]e ..."
5. Press insertHTML button to insert span
6. Word gets underlined
7. Select misspelled word, right-click on it and change it to one of suggested words.
   Result: both spans (red and misspelled) are removed but in editor elements path there is still span present and if you click on it JS error is thrown.

This may look like editor issue but IMO SCAYT should not remove red span. This is source of the error.

**Comment by wsc-bug-hunter** [comment]
Hello everyone,

I hope you are doing great!
We are reviewing the list of our open old issues and would like to clarify the status for this one. Could you please tell us if it is still actual and reproducible?

If so, could you please clarify a few steps?
1. ‘Open api.html sample ’ -> Could you please help us to find this file cause it looks like it was lost.
2. ‘insertHTML’ button -> Please clarify if this button available in default package or we need a special plugin.

Thank you. We are looking forward to your reply.

Regards,
WebSpellChecker

**Comment by wsc-julia-shaptala** [comment]
Since there is no response or additional information about the reported issue, we close it.
