### ISSUE TITLE
issue with CKEditor 4.3.2 with the SCAYT plugin

### ISSUE THREAD

**Issue by Michael31415926535897932384** [WebSpellChecker/ckeditor-plugin-scayt#37]
Hi,
I have an issue with CKEditor 4.3.2 (free) with the SCAYT plugin (free).
We don't like the double line spacing caused by P tags and have changed the setting config.enterMode = CKEDITOR.ENTER_BR; in the config.js file.
The trouble is that this causes the spell checker to move the cursor as you type.
For instance:
If I have a blank CKEditor, enter a character (say Q) and then move the cursor to the left of this character.
If I press enter it moves the cursor to AFTER the character.
If I then move the cursor up to the top of the page, it moves itself back down.
If I then turn the spell checker off this stops happening.
Is the config.enterMode = CKEDITOR.ENTER_BR; no longer supported?
Is there another way of stopping the double line spacing?
Or is this an issue with the spell checker?
Thanks
Michael

**Comment by tdi007** [comment]
I have a similar effect but here not words were deleted but the cursor jumps back to a word which was underlined by SCAYT. At the moment I dont found a way to reproduce, but it is definiteley randomly appearing ... 
We created 2 wysiwyg profiles ... one for editing bookpages and one for editing forum posts. This appears only in the forum posts and only sometimes. Forum posts are like comments in drupal.
I tried a little bit around with adapting the other plugins in CK Editor ... added some or reduce the amount of plugins, but nothing shows me a pattern. I changed the surface language too, but it is not always reproducable ...
It seems it is an issue of time point the user starts typing and the spell checker sets the red lines under the wrong words ...
Maybe it helps a little bit ... I attached a small video file and in the second part of it the issue occures sometimes ... (50 sec. to 1:05 min)

After I uploaded this video (please rename the PNG to .mp4) 
I think I found something interesting ... 
In the video you can see that I often reload the page with Ctrl+F5 and before the issue occurs you can see that the Editor is jumping to the top and additonally I scrolled with my mouse (wheel) up and down and I think I can reproduce the issue one times If I make this 5 times ... 

Use CKEditor 4.5.3.6c70c82 with wysiwyg 7.x-2.2+63-dev in Drupal 7.39
And bootstrap theme

![cursorjumpsback](https://cloud.githubusercontent.com/assets/15112274/10465234/06489318-71ee-11e5-89ab-0e117893de4e.png)

**Comment by tdi007** [comment]
Hi, I checked this issue and it seems it depends on loading the page means laoding the editor with active SCAYT ... I forgot to tell you, that SCAYT is automatically activated in my CK Editor and after 5/10 times Ctrl+F5 somethign seems to be not loaded corectly and this issue happens again ....
Another video file (rename from png to mp4 where the effect is much better seen ...
![cursorjumpsback1](https://cloud.githubusercontent.com/assets/15112274/10465900/955fece2-71f1-11e5-96ce-fdb6b29d74ed.png)

**Comment by WebSpellChecker** [comment]
Hi @tdi007 !

We`ve checked provided details and would like to ask you to clarify your request in more detailed way. Could you please provide us your version of browser.

**Comment by tdi007** [comment]
Hi, thanks for the feedback.
I used CHROME Version 45.0.2454.101 m

**Comment by WebSpellChecker** [comment]
@tdi007 This issue is already fixed hasn't include into the default CKEditor package yet. 
To avoid the issue you could rebuild CKEditor with new SCAYT plugin from master on GitHub. 
Please find the manual below:

1. Clone the CKEditor development repository hosted at GitHub:

 > git clone https://github.com/ckeditor/ckeditor-dev.git

2. Switch to the version that you need:

 > git checkout tags/your_version

3. Go to /plugins folder and clone SCAYT:

 > git clone https://github.com/WebSpellChecker/ckeditor-plugin-scayt.git scayt

4. Update config.js and dev/builder/build-config.js files with SCAYT plugin to include it into the CKEditor configuration:

 'scayt,' +
 and
 'scayt: 1'

5. Build CKEditor:

  > sh build.sh

6. Built CKEditor with updated SCAYT plugin is located in the 'release' folder
