### ISSUE TITLE
Cursor moves at the beginning of highlighted misspelled word after typing or pasting into editor

### ISSUE THREAD

**Issue by adelura** [WebSpellChecker/ckeditor-plugin-scayt#65]
Tested and confirmed in CKEditor 4.4.0 prerelease. Can not reproduce in 4.3.4
Browsers: All
1. Open some editor sample
2. Clear editor content
3. Enable SCAYT
4. Type sentence in editor "hello moto "
5. Wait until word "moto" is highlighted
   - Actual result: cursor moves at the beginning of selected word.

Screencasts:
http://goo.gl/14YSR8
http://goo.gl/1I9oEu

Plase note: as you can see in second screencast cursor moves at the beginning of first highlighted word.

**Comment by cbonami** [comment]
I can confirm that the bug is still there. At least in ckeditor 4.4.2 and scayt 4.6.2.
Reopen please.

**Comment by Reinmar** [comment]
CKEditor 4.4.2 is an old release. Can you reproduce it on the latest release?

**Comment by cbonami** [comment]
I'll check it out and let you know.
Please also note that:
- the scayt plugin is enabled at startup
- the problem only occurs the first ckeditor - instance that is loaded; subsequent instances don't suffer from the problem anymore
