### ISSUE TITLE
Misspelled words are excluded from selection when SCAYT marks them

### ISSUE THREAD

**Issue by Reinmar** [WebSpellChecker/ckeditor-plugin-scayt#75]
1. Open http://ckeditor.com/demo#inline
2. Clear contents of the top right editor.
3. Type `<p>abc abc</p><p>abc abc</p>`.
4. Press <kbd>CTRL+A</kbd>.
5. Enable SCAYT.
6. Selection is changed to `<p>abc[ abc</p><p>abc ]abc</p>` when "abc" words are underlined.

Reproducible on Chrome.

**Comment by wsc-julia-shaptala** [comment]
The priority for this issue changed from "normal" to "low". This one won't be fixed.
