### ISSUE TITLE
SCAYT causes formatting issues in ckeditor when "Wiris" editor is also part of the ckeditor plugin

### ISSUE THREAD

**Issue by roger31** [WebSpellChecker/ckeditor-plugin-scayt#81]
I am using the latest version [4.4.4] of CKEditor. I also use the following additional plugins, scayt and wiris. A coupe of issues i am facing

1) #11915: - although the release note claims that the cursor issue has been fixed, the issue exists in my application. I have configured the "scayt_autoStartup : true" in my application.

2) when i open the wiris editor and try to insert user selection, the "selected text/input" is inserted at the begining of the sentence rather than at the end of the sentence all the time. 

Note: both the above issues do not happen when the "SCAYT" is disabled

It will help if you can confirm what kind of configuration will resovle issue #1 and if issue #2 can also be resolved. Thanks

Note: as per the ckeditor team both the issues could be due to SCAYT plugin.

**Comment by wwalc** [comment]
No reply since 5 months, I guess the issue can be closed.
