### ISSUE TITLE
SCYAT puts the cursor at the beginning of the word if it has mistakes

### ISSUE THREAD

**Issue by artem-galas** [WebSpellChecker/ckeditor-plugin-scayt#83]
Hi,
I am using CKeditor, version 4.4.1 and SCYAT for spelling check. When there is an error in the word, the cursor jumps to the beginning of this word. Is it possible to fix it somehow and make the cursor stay where is?
I just tried it in the latest released CKeditor version (4.4.5) [demo](http://ckeditor.com/demo) and the issue is still there. 

Thanks, 
Artem.

**Comment by cperryk** [comment]
FWIW, I'm also experiencing this issue inside node-webkit. It only happens when SCAYT is enabled by default (i.e. scayt_autoStartup is set to true).

**Comment by WebSpellChecker** [comment]
Thank you for the information. Please provide:
1) exact steps
2) video if it's possible

**Comment by MayurKasture** [comment]
Hello Guys.,
    I facing the same with the cursor. I'm frusteted to solve this issue. please fix this ASAP. 

1) Browser : Google Chrome
2) When im using CKEditor in New window (window.open() in react js code base ) it fails in many more things. 
3) version of ckeditor : 8.0.0 with the React 18 version.
