### ISSUE TITLE
Errors thrown when focusing editor after specific operations

### ISSUE THREAD

**Issue by Reinmar** [WebSpellChecker/ckeditor-plugin-scayt#86]
With SCAYT 4.5 and IE8. Perhaps reproducible with other IEs.

1. Open replacebycode sample.
2. Enable SCAYT.
3. Place caret somewhere in the text (e.g in the header).
4. Pick some font color.
5. Type few characters.
6. Undo and redo.
7. Press the opt key and ESC. That should move the focus to the menu bar and back to the editor.
8. Errors are thrown. Editor becomes unusable.

I reproduced this with many scenarios, sometimes without the step 4 and with blurring editor in other ways. I think that undoing and redoing is the crucial step here.

**This is a regression.**

**Comment by WebSpellChecker** [comment]
Fix is on testing stage now and committed into scayt-dev branch.

**Comment by WebSpellChecker** [comment]
Fix has been verified and closed in our bug tracking system. It is expected to be merged into master branch in the middle of March in release version 4.7

**Comment by WebSpellChecker** [comment]
We're glad to inform you that the WebSpellChecker.net application has been released with version 4.7. The fix in the SCAYT plug-in is available in the master branch already.
