### ISSUE TITLE
Error thrown when moving between editors

### ISSUE THREAD

**Issue by Reinmar** [WebSpellChecker/ckeditor-plugin-scayt#88]
With **SCAYT 4.5**. Reproduced on IE9. This is a regression.

1. Open the jQuery adapter sample.
2. Focus the first editor and enable SCAYT.
3. Correct the "Aldrin" using the context menu.
4. Click inside the second editor.
5. Error is thrown.

```
SCRIPT87: Invalid argument. 
ckeditor.js, line 425 character 20
```

This is inside `element.getText()`.

**Comment by WebSpellChecker** [comment]
Fix is on testing stage now and committed into scayt-dev branch.

**Comment by WebSpellChecker** [comment]
Fix is available in the master branch
