### ISSUE TITLE
SCAYT gets disabled when opening and closing the template dialog

### ISSUE THREAD

**Issue by Reinmar** [WebSpellChecker/ckeditor-plugin-scayt#89]
1. Open replacebycode sample
2. Click the Scayt Button and "Enable SCAYT".
3. Click the Templates Button
4. Cancel or click X to close Templates Popup without selecting template

SCAYT Button in tool bar is disabled and SCAYT cannot be enabled any more.

I reproduced this with the SCAYT 21da635a as well as on CKEditor 4.4.5.

Reported in http://dev.ckeditor.com/ticket/12657

**Comment by WebSpellChecker** [comment]
We're glad to inform you that the fix is committed into master branch.
