### ISSUE TITLE
SCAYT is exposing globals in the documentation

### ISSUE THREAD

**Issue by Reinmar** [WebSpellChecker/ckeditor-plugin-scayt#97]
* http://docs.ckeditor.com/#!/api/DataStorage
* http://docs.ckeditor.com/#!/api/object.DataStorage

I think that these are just mistakes, but if you need a global object, then of course `SCAYT` or some similar namespace can be used.

**Comment by WebSpellChecker** [comment]
Thank you for reporting the issue. We're working on it and update you with the status when it'll be ready.

**Comment by WebSpellChecker** [comment]
We've started the fixing stage. The fix is scheduled to be released in version 4.8.

**Comment by WebSpellChecker** [comment]
Fix is ready and available in the scayt-dev and master branches.
