### ISSUE TITLE
SCAYT Affects Dialog Double Click

### ISSUE THREAD

**Issue by jswiderski** [WebSpellChecker/ckeditor-plugin-scayt#98]
Please see: http://dev.ckeditor.com/ticket/12996

To reproduce this issue just run CKEditor with scayt_autoStartup:true  and double click on the sample image in replacebycode.html sample page.

var editor = CKEDITOR.replace( 'editor1', {
	scayt_autoStartup  : true
});

**Comment by WebSpellChecker** [comment]
Thank you for reporting the issue. We're taking it into the next development sprint that is started on Monday (June 8).

**Comment by WebSpellChecker** [comment]
The issue has been fixed and release in the WebSpellChecker.net version 4.8. The fix is in the SCAYT CORE and already available for Hosted users.
