### ISSUE TITLE
Cursor jumps before a word after template dialog is opened and closed

### ISSUE THREAD

**Issue by Reinmar** [WebSpellChecker/ckeditor-plugin-scayt#99]
Followup for #89, before which template dialog was switching off SCAYT totally.

Now:

1. Enable SCAYT and make sure that some word is incorrect.
2. Open the template dialog and close it (cancel/X).
3. Place caret in some underlined word.
4. Start typing.

Result: Caret is moved before that word.

Testes on Chrome and https://github.com/ckeditor/ckeditor-presets/commit/17a7a7dc

**Comment by WebSpellChecker** [comment]
Thank you fro reporting the issue. It is submitted to QA team to reproduce.

**Comment by WebSpellChecker** [comment]
We've tried to reproduce issue with latest version of SCAYT plugin and CKEditor 4.4.8-dev. Issue hasn't been reproduced yet. Provided link does not contain an update to SCAYT plugin.
